server:
  port: 8080

spring:
  application:
    name: realtime-chat-app
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://singhgurcyber_db_user:Ef8RNaMi0sZbP5Uz@chatclustur.5b0wzoy.mongodb.net/chatapp?appName=ChatClustur}
      auto-index-creation: true

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000 # 24 hours
